/*
 * Fialka — Post-quantum encrypted messenger
 * Copyright (C) 2024-2026 DevBot667
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
package com.fialkaapp.fialka.data.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A single-use invite code for a private mailbox.
 * Generated by OWNER, expires after 24h, consumed on use.
 */
@Entity(
    tableName = "mailbox_invites",
    indices = [Index(value = ["expiresAt"])]
)
data class MailboxInvite(
    @PrimaryKey val code: String,
    val createdAt: Long,
    val expiresAt: Long,
    val used: Boolean = false,
    val usedByPubKey: String? = null
)
